"""add tutorial page config

Revision ID: e2d76e83d85e
Revises: m7n8o9p0q1r2
Create Date: 2026-03-30 08:28:33.348290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2d76e83d85e'
down_revision = 'm7n8o9p0q1r2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorial_page_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # Migration sebelumnya ter-generate dengan operasi drop table lain.
    # Kita STOP di sini supaya migrasi hanya menambah tabel tutorial_page_configs.
    return
    op.drop_table('supply_products')
    op.drop_table('supply_order_items')
    op.drop_table('supply_banners')
    op.drop_table('supply_units')
    op.drop_table('inventory_layers')
    op.drop_table('supply_orders')
    op.drop_table('supply_categories')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))
        batch_op.create_unique_constraint(None, ['key'])

    with op.batch_alter_table('inventory_cost_layer_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_usages_layer'))
        batch_op.drop_index(batch_op.f('ix_cost_usages_transaction_item'))

    with op.batch_alter_table('inventory_cost_layers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_layers_product_received'))
        batch_op.drop_index(batch_op.f('ix_cost_layers_tenant_product'))

    with op.batch_alter_table('lead_captures', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tenants', ['trial_tenant_id'], ['id'])

    with op.batch_alter_table('marketplace_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mkt_orders_seller'))
        batch_op.drop_index(batch_op.f('ix_mkt_orders_status'))
        batch_op.drop_index(batch_op.f('ix_mkt_orders_tenant'))

    with op.batch_alter_table('marketplace_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mkt_products_category'))
        batch_op.drop_index(batch_op.f('ix_mkt_products_seller'))

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_member_tenant_phone', ['tenant_id', 'telepon'])

    with op.batch_alter_table('operational_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operational_expenses_tenant_tanggal'))

    with op.batch_alter_table('product_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_audit_logs_product_created'))
        batch_op.drop_index(batch_op.f('ix_product_audit_logs_tenant_created'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_tenant_aktif'))

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_product_created_at'))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('kabupaten')

    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_items_transaction_id'))
        batch_op.drop_column('harga_beli_snapshot')

    with op.batch_alter_table('transaction_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_payments_method'))
        batch_op.drop_index(batch_op.f('ix_transaction_payments_tenant'))
        batch_op.drop_index(batch_op.f('ix_transaction_payments_trx'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_tenant_created_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_tenant_status_created_at'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_role_aktif'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutorial_page_configs')
    return
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tenant_role_aktif'), ['tenant_id', 'role', 'aktif'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_tenant_status_created_at'), ['tenant_id', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tenant_created_at'), ['tenant_id', 'created_at'], unique=False)

    with op.batch_alter_table('transaction_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_payments_trx'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_payments_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_payments_method'), ['method'], unique=False)

    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harga_beli_snapshot', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_transaction_items_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kabupaten', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_product_created_at'), ['product_id', 'created_at'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_tenant_aktif'), ['tenant_id', 'aktif'], unique=False)

    with op.batch_alter_table('product_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_audit_logs_tenant_created'), ['tenant_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_audit_logs_product_created'), ['product_id', 'created_at'], unique=False)

    with op.batch_alter_table('operational_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operational_expenses_tenant_tanggal'), ['tenant_id', 'tanggal'], unique=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint('uq_member_tenant_phone', type_='unique')

    with op.batch_alter_table('marketplace_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mkt_products_seller'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mkt_products_category'), ['category_id'], unique=False)

    with op.batch_alter_table('marketplace_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mkt_orders_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mkt_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mkt_orders_seller'), ['seller_id'], unique=False)

    with op.batch_alter_table('lead_captures', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('inventory_cost_layers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_layers_tenant_product'), ['tenant_id', 'product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_layers_product_received'), ['product_id', 'received_at', 'id'], unique=False)

    with op.batch_alter_table('inventory_cost_layer_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_usages_transaction_item'), ['transaction_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_usages_layer'), ['layer_id'], unique=False)

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    op.create_table('supply_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('urutan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aktif', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('supply_categories_pkey'))
    )
    op.create_table('supply_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nomor', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('catatan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('alamat_kirim', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('supply_orders_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('supply_orders_pkey')),
    sa.UniqueConstraint('nomor', name=op.f('supply_orders_nomor_key'))
    )
    op.create_table('inventory_layers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('po_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('harga_beli', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('qty_initial', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('qty_remaining', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['po_item_id'], ['purchase_order_items.id'], name=op.f('inventory_layers_po_item_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('inventory_layers_product_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('inventory_layers_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_layers_pkey'))
    )
    op.create_table('supply_units',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('supply_units_pkey')),
    sa.UniqueConstraint('nama', name=op.f('supply_units_nama_key'))
    )
    op.create_table('supply_banners',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('judul', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('gambar', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('urutan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aktif', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('supply_banners_pkey'))
    )
    op.create_table('supply_order_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nama_snapshot', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('harga_snapshot', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['supply_orders.id'], name=op.f('supply_order_items_order_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['supply_products.id'], name=op.f('supply_order_items_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('supply_order_items_pkey'))
    )
    op.create_table('supply_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('deskripsi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('satuan', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('harga', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('stok', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('aktif', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('foto', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['supply_categories.id'], name=op.f('supply_products_category_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('supply_products_pkey'))
    )
    op.drop_table('tutorial_page_configs')
    # ### end Alembic commands ###
